### PR TITLE
Implement secp256k1 keys

### PR DESCRIPTION
**Pull request by vyzo**
This PR implements support for secp256k1 keys [#19], complementing  https://github.com/libp2p/js-libp2p-crypto/pull/60 and https://github.com/libp2p/js-libp2p-crypto-secp256k1/pull/1

The implementation uses the [btcec](https://github.com/btcsuite/btcd/tree/master/btcec) package from btcd.
This needs to be vendored in gx, without pulling everything under btcd (it is desigend to be a self-contained package).

@whyrusleeping what's the recommended process for vendoring this external dependency into gx?

### CODE REVIEW

**Comment by parkan** [comment]
Would love to get this merged in if possible

**Comment by Kubuxu** [comment]
The github.com/btcsuite/btcd/btcec has to be vendored using gx.

I created fork in https://github.com/gxed/btcd

Please create package.json in its btcec directory and publish it to gx.

**Comment by whyrusleeping** [comment]
I should probably create a guide on best practices for doing this

**Comment by vyzo** [comment]
PR for gx package: https://github.com/gxed/btcd/pull/1
package btcec published with hash: QmRoGBYPVMwxPyyEQuMYXBFbXPN1xRYag4CwSBvRWYrKxR

**Comment by vyzo** [comment]
Actually, the hash is different after running release:
package btcec published with hash: Qmct7apXgRK66hqvdokDLtPuZWp2zWPtQ4P2gJjdbtsSS3

**Comment by parkan** [comment]
gx PR in!

**Comment by parkan** [comment]
@whyrusleeping another friendly poke 👈

**Comment by whyrusleeping** [comment]
@parkan sorry for the delay! I wasnt getting notifications for this for some reason...

**Comment by Kubuxu** [comment]
Yeah, 1.3M of that is just one file that encodes the secp points.

**Comment by Kubuxu** [comment]
That are already packed and compressed. If I ever meet DJB in person, I will thank him so much for x25519.

**Pull request merged**
