### PR TITLE
libp2p badges, remove IPFS

### PR DESCRIPTION
**Pull request by ghost**
Tidying up README for the new year.

### CODE REVIEW

**Comment by Stebalien** [comment]
So, I *believe* this is OK because the only thing the apache license adds is a patent grant from *us* (I think?). However, we should run this by a lawyer.

**Comment by mgoelzer** [comment]
It's the advice from @ianjdarrow for all PL-sponsored projects.

**Comment by Stebalien** [comment]
But did he recommend transitioning *existing* projects with non-PL contributors?

**Comment by Stebalien** [comment]
> Yes, our goal is to transition every libp2p repo to dual license.

It's just that *re*-licensing *usually* requires permission from contributors as, unless otherwise specified through a copyright assignment, copyright is retained by the *author* (not transferred to us).

**Review by Stebalien — APPROVED** [review]

**Pull request merged**
